#include<iostream>
#include<string.h>
using namespace std;
int main(){
  //Greater Number Progarm-----------------------------------------------------------------------
		int f,s;
		cout<<"Enter 1st Numbar";
		cin>>f;
		cout<<"Enter 2nd Numbar ";
		cin>>s;
		if(f>s){
			cout<<"F 1st no is Greater Then G2 nd no ";
		}
		if(s>f){
			cout<<"G 2nd no is greater Then F 1st no";
			
		}	
		if(f==s){
			cout<<" Both Are Equal ";
		}
	return 0;
}
